---
# Playbook to uninstall K3s from all nodes in the cluster
- name: Uninstall K3s from agent nodes
  hosts: agents
  become: true
  # Process one agent at a time
  serial: 1
  tasks:
    - name: Run K3s agent uninstall script
      shell: /usr/local/bin/k3s-agent-uninstall.sh
      ignore_errors: true
      register: agent_uninstall

    - name: Check if uninstall was successful
      debug:
        msg: "Agent uninstall on {{ inventory_hostname }} completed with status: {{ 'Success' if agent_uninstall.rc == 0 else 'Failed - ' + agent_uninstall.stderr }}"

    - name: Check if K3s agent service exists
      stat:
        path: /etc/systemd/system/k3s-agent.service
      register: agent_service_check

    - name: Report agent service status
      debug:
        msg: "K3s agent service on {{ inventory_hostname }}: {{ 'Removed' if not agent_service_check.stat.exists else 'Still present' }}"

    - name: Clean up K3s directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/rancher/k3s
        - /var/lib/rancher/k3s
      ignore_errors: true

- name: Uninstall K3s from control plane nodes
  hosts: control_plane
  become: true
  # Process one control plane node at a time
  serial: 1
  tasks:
    - name: Run K3s server uninstall script
      shell: /usr/local/bin/k3s-uninstall.sh
      ignore_errors: true
      register: server_uninstall

    - name: Check if uninstall was successful
      debug:
        msg: "Server uninstall on {{ inventory_hostname }} completed with status: {{ 'Success' if server_uninstall.rc == 0 else 'Failed - ' + server_uninstall.stderr }}"

    - name: Check if K3s server service exists
      stat:
        path: /etc/systemd/system/k3s.service
      register: server_service_check

    - name: Report server service status
      debug:
        msg: "K3s server service on {{ inventory_hostname }}: {{ 'Removed' if not server_service_check.stat.exists else 'Still present' }}"

    - name: Clean up K3s directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/rancher/k3s
        - /var/lib/rancher/k3s
      ignore_errors: true
